//File for public functions that are actions, such as "I_do_this"

to I_open_the_keepass_vault with vaultPath:"C:\Users\lucibill\OneDrive - Keysight Technologies\Documents\Keepass\test-EPF.kdbx"
	logFct vaultPath
	set myProgram to <<"C:\Program Files\KeePass Password Safe 2\KeePass.exe">> 
	"steps/common/action".I_execute_this_windows_r_command myProgram && quote & vaultPath & quote
	
	WaitFor 8.0, "apps/keepass/masterpassword_input_logo"
	wait 0.5
	
	set cryptKey to "steps/common/_lib"._get_cryptkey
	set encodedSecret to "TZCSfHeXQARHBS[WMULXHD\MOUJFSZbJEN@ePLGgUJDX>J>IQFRQ=KPVVWWXW\Jd"
	
	TypeHiddenText DecodeText(encodedSecret, cryptKey)
	
	typeText  returnkey
	
	WaitFor 25, "apps/keepass/keepasslogo_topmenu"
	WaitFor 20, "apps/keepass/icon_lockworkspace"
	
	logFct	
end I_open_the_keepass_vault

to I_use_the_autotype_for_the_credentials with myEntry:"GitHub with OTP"
	logFct myEntry
	do_click myEntry
	wait 0.5
	TypeText controlKey, "v"
	wait 5	
	logFct
end I_use_the_autotype_for_the_credentials

to I_copy_paste_the_OTP_code_of_the_current_entry
	logFct
	TypeText altKey, tabKey
	wait 2
	
	TypeText controlKey, "t"
	
	wait 0.5
	
	TypeText altKey, tabKey
	wait 1
	TypeText shiftKey, insertkey
	TypeText returnKey
	
	logFct
end I_copy_paste_the_OTP_code_of_the_current_entry

to I_close_Keepass
	logFct
	typeText altKey, f4
	wait 1
	repeat 10 times
		if not ImageFound(imageName:"apps/keepass/icon_taskbar", waitFor:1) then
			logFct
			return
		end if
		
		wait 2
	end repeat
	
	Throw "Failed to quit Keepass", "The keepass icon is still visible in the taskbar"
end I_close_Keepass