//File for public functions that are actions, such as "I_do_this"

to I_open_chrome with optionalURL:"about:blank"
	logFct optionalURL
	"steps/common/action".I_launch_browser_x_at_url_y "chrome", optionalURL
	logFct
end I_open_chrome

to I_close_chrome
	logFct
	typeText altKey, f4
	wait 1
	
	set is_ok to false
	repeat 10 times
		if not ImageFound(imageName:"browser/chrome/icon_taskbar", waitFor:1) then
			set is_ok to true
			exit repeat
		end if
		
		wait 2
	end repeat
	
	if not is_ok then
		Throw "Failed to quit Chrome", "It looks like the Chrome icon is still visible in the task bar"
	end if
	
	logFct
end I_close_chrome