//Fichier pour les fonctions publiques de type action

to j_ouvre_une_nouvelle_session_chrome with myOptions:{}
	logFct myOptions
	"steps/common/action".je_lance_le_navigateur_x "chrome", myOptions
	logFct
end j_ouvre_une_nouvelle_session_chrome

to je_ferme_chrome
	logFct
	typeText altKey, f4
	wait 1
	repeat 5 times
		if not ImageFound(imageName:"browser/chrome/icon_taskbar", waitFor:2) then
			logFct
			return
		end if
		
		wait 2
	end repeat
	
	Throw "Quitter Chrome : échec", "L'icone de Chrome est encore présente dans la barre des taches"
	
end je_ferme_chrome