to je_cree_un_nouveau_fichier
	logFct
	wait 3
	MoveTo text:"en-US", waitFor:30
	cliquer "apps/vscode_online/create_new_file"
	wait 2
	// note : j'utilise un "getter" plutot qu'un appel direct à la variable globale, pour 2 raisons : 
	// 1) avec la fonction, j'ai l'auto-completion.
	// 2) avec la fonction, si je fais une faute de frappe, ça plante. Tandis qu'avec une variable,
	//     si je fais une faute de frappe dans le nom, ça retourne une valeur vide et ça ne plante
	//     pas directement, mais plus tard (c'est plus compliqué à débogger)
	typeText "steps/vscode_online/_lib"._get_default_newfile_name(), returnkey
	wait 2
	typeText "this is a new file!", returnkey
	WaitFor 4, text:"this is a new file!"
	logFct	
end je_cree_un_nouveau_fichier

to je_supprime_le_nouveau_fichier
	logFct
	cliquerDroit "steps/vscode_online/_lib"._get_default_newfile_name(), SearchRectangle:[0,92,350, RemoteScreenSize().y]
	wait 1
	cliquer "Delete Permanently", waitfor: 5, SearchRectangle:empty
	wait 1
	Attendre "Are you sure you want to permanently delete"
	typeText returnkey	
	logFct
end je_supprime_le_nouveau_fichier

to je_ferme_vscode_online
	logFct
	typeText controlKey, "w"
	
	if ImageFound(text:"Leave site?", waitFor:4) then
		typeText returnKey
	end if
	
	set isExitOK to false
	Repeat 5 times
		if not ImageFound(imageName:"apps/vscode_online/topleft_logo.png", waitFor:0) then
			set isExitOK to true
			exit repeat
		end if
		
		wait 2
	End repeat
	
	if not isExitOK then Throw "Impossible de quitter VS Code Online", "L'opération a échoué"
	logFct
end je_ferme_vscode_online