//File for internal functions. Anything that does not appear explicitely in a "Gherkin" style test


to _check_value_x_is_in_list_y with myValue:"", myList:[]
	if myValue is not in myList then Throw "Value is not in list", "The value '" & myValue & "' does not belong to this list:" && myList
	return myValue
end _check_value_x_is_in_list_y

to _get_cryptkey
	set secretKey to env("EPF_SECRET_KEY") // Variable d'environnement système
	// Alternative possible : ppasser par le gestionnaire de mot de passe réseau de Windows
	
	// // SetVaultValue "EPF_SECRET_KEY", "this is a super secret key, don't leav it here or it will leak"	
	// set secretKey to  GetVaultValue("EPF_SECRET_KEY")
	
	if secretKey is empty then
		Throw "Missing env. variable", "the environment variable 'EPF_SECRET_KEY' must not be empty"
	end if
	
	return secretKey
end _get_cryptkey