//File for internal functions. Anything that does not appear explicitely in a "Gherkin" style test

to _get_default_test_repo
	return "https://github.com/lucienbill/obsidian-daily-notes"
end _get_default_test_repo

to _ensure_disconnection
	logFct openNewChromeSession
	// === Default values and behaviours ===
	set url_github to "https://github.com/logout"
	
	// Select the URL bar
	typeText escapeKey
	moveto [500,500]
	typeText F6
	wait 0.5
	typeText url_github, returnKey
	
	wait 2
	
	// Make sure that we are on GitHub, and not logged-in
	repeat 10 times
		if ImageFound(text:"Select account to sign out", waitFor:0) then
			do_click "Sign out from all accounts"
			wait 2
		end if
		
		if ImageFound(text:"Sign in", waitFor:0) then
			logFct
			return
		end if
		
		wait 2
	end repeat
	
	Throw "Failed to access Github in a 'disconnected' state", "When accessing GitHub or trying to log out, an error occured"
end _ensure_disconnection