// In the Suite's Settings, make sure that this scripts is executed firs:
// Click on "Settings..." (bottom left of the editor window)
// Then check these bixes:
//   - "Before each run, execute this script:"
//   - "Before running a selection, execute:"
// In the dropdown menu of the elements, select "_config.script"

########## This part is specific to my machine (French laptop) ##########
set the sendShiftForCaps to no // for my azerty keyboard
set the ScriptLogging to yes
########## End my the part that is specific to my machine ##########

// import custom functions
// (note: they don't appear natively in the autocompletion, I added suite snippets manually)
Start Using "steps/eggplant/custom_functions"