// Some basic unit tests, to make sure my complex code actually works
Connect serverID:"TutorialSUT", portNum:5900

set counter to 0
set defaultImageUpdate to the ImageUpdate
Set the ImageUpdate to Off

// instructions that must work
set listOfTests_ok to [
	// do_click
	<<do_click "unitTests/battery_full">>,
	<<do_click {image:"unitTests/battery_full", waitfor:0}>>,
	<<do_click {imageName:"unitTests/battery_full", waitfor:0}>>,
	<<do_click {textOrImage:"unitTests/battery_full", waitfor:0}>>,
	<<do_click "unitTests/battery_full.png">>,
	<<do_click {image:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_click {imageName:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_click {textOrImage:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_click "Not a real phone">>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:true}>>,
	<<do_click {text:"Not a real phone", waitfor:0, caseSensitive:true}>>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:true, SearchRectangle:(14,175,369,275)}>>,
	<<do_click {text:"Not a real phone", waitfor:0, caseSensitive:true, SearchRectangle:(14,175,369,275)}>>,
	<<do_click "unitTests/battery_full">>,
	<<do_click "unitTests/collection">>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false}>>,
	<<do_click {text:"Not a real phone", waitfor:0, caseSensitive:false}>>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false, SearchRectangle:(14,175,369,275)}>>,
	<<do_click {text:"Not a real phone", waitfor:0, caseSensitive:false, SearchRectangle:(14,175,369,275)}>>,
	<<do_click text:<2 digits, ":", 2 digits>, SearchRectangle:[117,0,278,32]>>,
	<<do_click textOrImage:"unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_click "unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_click {textOrImage:<2 digits, ":", 2 digits>}>>,
	<<do_click "phone", caseSensitive:false>>,
	<<do_click "unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false}, {validCharacters:"*"}>>,
	<<do_click textOrImage:"phone", caseSensitive:false>>,
	<<do_click {textOrImage:"phone", caseSensitive:false}, {validwords:"*"}>>,
	<<do_click "phone", caseSensitive:false>>,
	<<do_click "phone", {caseSensitive:false}>>,
	
	// waitfor
	<<do_waitfor "unitTests/battery_full">>,
	<<do_waitfor {image:"unitTests/battery_full", waitfor:0}>>,
	<<do_waitfor {imageName:"unitTests/battery_full", waitfor:0}>>,
	<<do_waitfor {textOrImage:"unitTests/battery_full", waitfor:0}>>,
	<<do_waitfor "unitTests/battery_full.png">>,
	<<do_waitfor {image:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_waitfor {imageName:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_waitfor {textOrImage:"unitTests/battery_full.png", waitfor:0}>>,
	<<do_waitfor "Not a real phone">>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:true}>>,
	<<do_waitfor {text:"Not a real phone", waitfor:0, caseSensitive:true}>>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:true, SearchRectangle:(14,175,369,275)}>>,
	<<do_waitfor {text:"Not a real phone", waitfor:0, caseSensitive:true, SearchRectangle:(14,175,369,275)}>>,
	<<do_waitfor "unitTests/battery_full">>,
	<<do_waitfor "unitTests/collection">>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false}>>,
	<<do_waitfor {text:"Not a real phone", waitfor:0, caseSensitive:false}>>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false, SearchRectangle:(14,175,369,275)}>>,
	<<do_waitfor {text:"Not a real phone", waitfor:0, caseSensitive:false, SearchRectangle:(14,175,369,275)}>>,
	<<do_waitfor text:<2 digits, ":", 2 digits>, SearchRectangle:[117,0,278,32]>>,
	<<do_waitfor textOrImage:"unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_waitfor "unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_waitfor {textOrImage:<2 digits, ":", 2 digits>}>>,
	<<do_waitfor "phone", caseSensitive:false>>,
	<<do_waitfor "unitTests/battery_full.png", SearchRectangle:[318,0,426,90]>>,
	<<do_waitfor "phone", caseSensitive:false, {caseSensitive:false}>>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false}, {validCharacters:"*"}>>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false}, {validCharacters:"*"}>>,
	<<do_waitfor textOrImage:"phone", caseSensitive:false>>,
	<<do_waitfor {textOrImage:"phone", caseSensitive:false}, {validwords:"*"}>>,
	<<do_waitfor "phone", caseSensitive:false>>,
	<<do_waitfor "phone", {caseSensitive:false}>>,
]



// instructions that must throw an error
set listOfTests_ko to [
	// do_click
	<<do_click "browser/chrome/reloadIcon/", {waitfor:0}>>,
	<<do_click "ce texte n'est pas présent sur l'écran", {waitfor:0}>>,
	<<do_click empty, {imagename:"wrong_path", waitfor:0}>>,
	<<do_click empty>>,
	<<do_click {textOrImage:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_click {image:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_click {imageName:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_click {textOrImage:"ce texte n'est pas présent sur l'écran", waitfor:0}>>,
	<<do_click {text:"ce texte n'est pas présent sur l'écran", waitfor:0}>>,
	<<do_click {image:"wrong_path", waitfor:0}>>,
	<<do_click {imagename:"wrong_path", waitfor:0}>>,
	<<do_click {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false, text:"Not a real phone"}>>,
	<<do_click "phone",  "phones">>,
	// waitfor
	<<do_waitfor "browser/chrome/reloadIcon/", {waitfor:0}>>,
	<<do_waitfor "ce texte n'est pas présent sur l'écran", {waitfor:0}>>,
	<<do_waitfor empty, {imagename:"wrong_path", waitfor:0}>>,
	<<do_waitfor empty>>,
	<<do_waitfor {textOrImage:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_waitfor {image:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_waitfor {imageName:"browser/chrome/reloadIcon/", waitfor:0}>>,
	<<do_waitfor {textOrImage:"ce texte n'est pas présent sur l'écran", waitfor:0}>>,
	<<do_waitfor {text:"ce texte n'est pas présent sur l'écran", waitfor:0}>>,
	<<do_waitfor {image:"wrong_path", waitfor:0}>>,
	<<do_waitfor {imagename:"wrong_path", waitfor:0}>>,
	<<do_waitfor {textOrImage:"Not a real phone", waitfor:0, caseSensitive:false, text:"Not a real phone"}>>,
	<<do_waitfor "phone", "phones">>,	
]

// instructions that must return true
set listOfTests_true to []

// instructions that must return false
set listOfTests_false to []

Repeat with each item myInstruction of listOfTests_ok
	set tc_name to "Unit_Test_" & counter & "_expect_OK : " & myInstruction
	BeginTestCase tc_name
	logWarning myInstruction.text
	Try
		send myInstruction.text to SenseTalk
	Catch theException
		LogError theException 
	End try
	EndTestCase tc_name
	
	add 1 to counter
End repeat

Repeat with each item myInstruction of listOfTests_ko
	set tc_name to "Unit_Test_" & counter & "_expect_Expection : " & myInstruction
	BeginTestCase tc_name
	logWarning myInstruction.text
	Try
		send myInstruction.text to SenseTalk
		logError "This should have thrown an exepction: " && myInstruction
	Catch theException
		// noop; OK
		LogSuccess "The statement throwed an exception (as it should have)"
	End try
	EndTestCase tc_name
	
	add 1 to counter
End repeat

Disconnect
Set the ImageUpdate to defaultImageUpdate

