// Feature: open VS Code Online from a github repo

BeginTestCase "Attempt to open VS Code online without being logged into Github"
"steps/common/validation".I_check_that_the_Windows_SUT_is_available
"steps/chrome_browser/action".I_open_chrome
"steps/github/action".I_go_to_github_and_make_sure_I_am_disconnected
"steps/github/action".I_go_to_the_test_repo "https://github.com/lucienbill/obsidian-daily-notes"
"steps/github/action".I_attempt_to_open_vs_code_online
"steps/github/validation".I_check_that_vs_code_is_not_opened
EndTestCase "Attempt to open VS Code online without being logged into Github"

//-----

BeginTestCase "Log into Github, then open VS Code online"
"steps/github/action".I_log_into_github
"steps/github/action".I_attempt_to_open_vs_code_online
"steps/vscode_online/validation".I_check_that_vs_code_onlinde_is_opened
"steps/vscode_online/action".I_create_a_new_file
"steps/vscode_online/action".I_delete_the_new_file
EndTestCase "Log into Github, then open VS Code online"

//-----

BeginTestCase "Close everything"
"steps/vscode_online/action".I_close_VS_Code_online
"steps/github/action".I_disconnect_from_github
"steps/chrome_browser/action".I_close_chrome
"steps/keepass/action".I_close_Keepass
EndTestCase "Close everything"

